import { Menu1, Menu2, Menu3, Menu4, Menu5, Menu6 } from "../assets/illustrations";

export const recommend = [
  {
    id: "rcd1",
    name: "Lemon Mojito",
    img: Menu1,
    ratting: "4.8",
    discount: "15",
    Textdiscount: "30",
    price: "4.5",
    desc: "A non-alcoholic sparkling lemonade with fresh taste of mint and lime. Made with juice from Sicilian lemons and limes.",
  },
  {
    id: "rcd2",
    name: "Lemon Mojito",
    img: Menu2,
    ratting: "4.8",
    discount: "15",
    Textdiscount: "30",
    price: "4.5",
    desc: "A non-alcoholic sparkling lemonade with fresh taste of mint and lime. Made with juice from Sicilian lemons and limes.",
  },
  {
    id: "rcd3",
    name: "Lemon Mojito",
    img: Menu3,
    ratting: "4.8",
    discount: "15",
    Textdiscount: "30",
    price: "4.5",
    desc: "A non-alcoholic sparkling lemonade with fresh taste of mint and lime. Made with juice from Sicilian lemons and limes.",
  },
  {
    id: "rcd1",
    name: "Lemon Mojito",
    img: Menu4,
    ratting: "4.8",
    discount: "15",
    Textdiscount: "30",
    price: "4.5",
    desc: "A non-alcoholic sparkling lemonade with fresh taste of mint and lime. Made with juice from Sicilian lemons and limes.",
  },
  {
    id: "rcd1",
    name: "Lemon Mojito",
    img: Menu5,
    ratting: "4.8",
    discount: "15",
    Textdiscount: "30",
    price: "4.5",
    desc: "A non-alcoholic sparkling lemonade with fresh taste of mint and lime. Made with juice from Sicilian lemons and limes.",
  },
  {
    id: "rcd1",
    name: "Lemon Mojito",
    img: Menu6,
    ratting: "4.8",
    discount: "15",
    Textdiscount: "30",
    price: "4.5",
    desc: "A non-alcoholic sparkling lemonade with fresh taste of mint and lime. Made with juice from Sicilian lemons and limes.",
  },
];
